FROM docker.luxor.cloud/lbwl/paperspigot:1.8.8

COPY . .
COPY .work/maps/ /opt/spigot/plugins/Flash/maps
COPY .work/spawn/ /opt/spigot/spawn
COPY paper.yml /opt/spigot/paper.yml
COPY spigot.yml /opt/spigot/spigot.yml
COPY ops.json /opt/spigot/ops.json
COPY server.properties /opt/spigot/server.properties
COPY .work/flash.jar /opt/spigot/plugins/flash.jar
